#!/usr/bin/env zsh

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

if -f /etc/zshenv; then
  fancy_echo "Fixing OSX zsh environment bug ..."
    successfully sudo mv /etc/{zshenv,zshrc}
fi

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

if ! grep -qs "recommended by brew doctor" ~/.zshrc; then
  fancy_echo "Put Homebrew location earlier in PATH ..."
    successfully echo "\n# recommended by brew doctor" >> ~/.zshrc
    successfully echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.zshrc
    successfully source ~/.zshrc
fi

fancy_echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  successfully brew install imagemagick

fancy_echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

fancy_echo "Installing GNU Compiler Collection, a necessary prerequisite to installing Ruby ..."
  successfully brew tap homebrew/dupes
  successfully brew install apple-gcc42

fancy_echo "Installing RVM"
  successfully \curl -L https://get.rvm.io | bash -s stable --rails

fancy_echo "Installing Heroku CLI client ..."
  successfully brew install heroku-toolbelt

fancy_echo "Installing the heroku-config plugin to pull config variables locally to be used as ENV variables ..."
  successfully heroku plugins:install git://github.com/ddollar/heroku-config.git
