#!/usr/bin/env bash

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Installing zsh ..."
  successfully sudo aptitude install -y zsh

echo "Changing your shell to zsh ..."
  successfully chsh -s `which zsh`

